instant_messaging/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'chatroom#index'
  get 'login', to:'sessions#new'
  post "login", to: 'sessions#create'
end
 

instant_messaging/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

instant_messaging/app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    validates :message, presence:true

end

instant_messaging/app/models/user.rb
class User < ApplicationRecord
    has_many :messages
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :username, presence:true, uniqueness:true, length: { minimum:3, maximum:50}
    validates :email, presence:true, uniqueness:true, format: { with: VALID_EMAIL_REGEX }
    has_secure_password
end

instant_messaging/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

instant_messaging/app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
    
    def index
        @messages = Message.all
    end

end

instant_messaging/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new

    end

    def create
        user = User.find_by(username: params[:session][:username])
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:success] = "You have now been logged in!"
            redirect_to root_path
        else
            flash[:error] = "Invalid credentials"
            render 'new'
        end
    end
end

instant_messaging/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new()
    end

    def create
        @user = User.create(user_params)
        if @user.save
            flash[:success] = "You have successfully signed up"
            redirect_to 'index'
        else
            render 'new'
        end

    end

    private
    def user_params
        params.require(:users).permit(:username, :email, :password)
    end

end

instant_messaging/app/helpers/application_helper.rb
module ApplicationHelper
end

instant_messaging/app/views/chatroom/index.html.erb
<h2 align= "center">Welcome to ChatMe </h2>
<h4 class="ui center aligned icon header">
  <i class="circular blue smile outline icon"></i>
</h4>

<p style="text-align:center"> Say something to your friends!</p>

<div class="ui two column grid">
    <div class="twelve wide column">
        <div class="ui fluid raised card chatbox">
            
                <div class = "content">
                    <%= render @messages %>
                </div>
                <div class="extra content">
                    <div class="ui fluid action input">
                        <input type="text" placeholder="Say something...">
                        <div class="ui blue button"><i class="large comments  icon"></i></div>
                    </div>
                </div>
            
        </div>
    </div>
    <div class="four wide column">
        
            <div class="ui fluid raised card chatbox">
                <div class="content">
                    <div class="ui inverted blue vertical menu">
                    <a class="active item">
                        Home
                    </a>
                    <a class="item">
                        Messages
                    </a>
                    <a class="item">
                        Friends
                    </a>
                    </div>
                    
                </div>
            </div>
        
    </div>
</div>

instant_messaging/app/views/layouts/_navigation.html.erb
<div class="ui blue inverted menu">
    <div class="ui container">
        <a class="active item" href="/">
            <i class="users icon"></i>    
            Chatroom
        </a>
        <a class="item">
            <i class="envelope icon"></i>
                Messages
        </a>
        <div class="right menu">
            <div class="ui dropdown item">
            Account <i class="dropdown icon"></i>
            <div class="menu">
                <%= link_to 'Login', login_path, class:"item" %>
                <a class="item">Logout</a>
                <a class="item">Signup</a>
            </div>
            </div>
            <div class="item">
                <div class="ui primary button">Sign Up</div>
            </div>
        </div>
    </div>
</div>

instant_messaging/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatMe!</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="ui container">
      <%= yield %>
    </div>
  </body>
</html>

instant_messaging/app/views/messages/_message.html.erb
<div class="ui feed">
    <div class="event">
        <div class="content">
            <div class="summary">
                <em><span class = "username"> <%=message.user.username%></span>: </em> <%= message.message%>
            </div>
        
        </div>
    </div>
</div>