config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#new'

  get 'chatroom', to: 'chatroom#index'
  get 'login', to:'sessions#new'
  post "login", to: 'sessions#create'
  delete "logout", to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'

  resource :users, except:[:new, :create]

  post "message", to: 'messages#create'

  mount ActionCable.server, at: '/cable'

end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    validates :message, presence:true
    scope :custom_display, -> { order(:created_at).last(20)}
end

app/models/user.rb
class User < ApplicationRecord
    has_many :messages
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :username, presence:true, uniqueness:true, length: { minimum:3, maximum:50}
    validates :email, presence:true, uniqueness:true, format: { with: VALID_EMAIL_REGEX }
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user 
    end

    def require_user
        if !logged_in?
            flash[:error] = "You need to be logged in to perform that action."
            redirect_to login_path
        end
    end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
    
    before_action :require_user

    def index
        @message = Message.new()
        @messages = Message.custom_display
    end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

    before_action :require_user
    def create
        message = current_user.messages.build(message_params)
        if message.save
            ActionCable.server.broadcast "chatroom_channel", 
                                        mod_message: message_render(message)
        end
    end

    private
    def message_params
        params.require(:message).permit(:message)
    end

    def message_render(message)
        render(partial: 'message', locals: {message: message})
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    before_action :logged_in_redirect, only: [:new, :create]
    before_action :log_out_redirect, only:[:destroy]

    def new

    end

    def create
        user = User.find_by(username: params[:session][:username])
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:success] = "You have now been logged in!"
            redirect_to chatroom_path
        else
            flash.now[:error] = "Invalid credentials"
            render 'new'
        end
    end

    def destroy
        flash[:success] = "You have now been logged out"
        session[:user_id] = nil
        redirect_to root_path
    end

    private
    def logged_in_redirect
        if logged_in?
            flash[:error] = "You are already logged in!"
            redirect_to chatroom_path
        end
    end

    def log_out_redirect
        if !logged_in?
            flash[:error] = "You need to be logged in to performo that action!"
            redirect_to login_path
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new()
    end

    def create
        @user = User.create(user_params)
        if @user.save
            flash[:success] = "You have successfully signed up"
            session[:user_id] = @user.id
            redirect_to chatroom_path
        else
            render 'new'
        end

    end

    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def flash_class(level)
        case level
          when 'notice' then "ui info message"
          when 'success' then "ui positive message"
          when 'error' then "ui negative message"
        end
      end
end

app/views/chatroom/index.html.erb
<h2 align= "center">Welcome to ChatMe </h2>
<h4 class="ui center aligned icon header">
  <i class="circular blue smile outline icon"></i>
</h4>

<p style="text-align:center"> Say something to your friends!</p>

<div class="ui two column grid">
    <div class="twelve wide column">
        <div class="ui fluid raised card chatbox">
            <div class = "content" id="messages">
                <div class="ui feed" id="message-container">
                    <%= render @messages %>
                </div>
            </div>
            <div class="extra content">
                <%= form_for(@message, html: {class:"ui reply form", role:"form"}, url: message_path, remote: true) do |f|%>
                    <div class="ui fluid input">
                        <%= f.text_field :message %>
                        <%= f.button '<i class="large blue comments  icon"></i>'.html_safe %>
                    </div>
                <% end %>    
            </div>
            
        </div>
    </div>
    <div class="four wide column">
        
            <div class="ui fluid raised card chatbox">
                <div class="content ui grid ">
                    <div class="ui inverted blue vertical menu right-nav">
                    <a class=" item">
                        Home
                    </a>
                    <a class="item">
                        Messages
                    </a>
                    <a class="item">
                        Friends
                    </a>
                    </div>
                    
                </div>
            </div>
        
    </div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %> transition">
        <i class="close icon"></i>
      <%= value %>
    </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="ui blue inverted menu">
    <div class="ui container">
        <a class="active item" href="/">
            <i class="users icon"></i>    
            Chatroom
        </a>
        <a class="item">
            <i class="envelope icon"></i>
                Messages
        </a>
        <div class="right menu">
            <div class="ui dropdown item">
                Account <i class="dropdown icon"></i>
                <div class="menu">
                    <% if logged_in? %>
                        <%= link_to 'Logout', logout_path, class:"item", method: :delete %>
                    <% else %>
                        <%= link_to 'Login', login_path, class:"item" %>
                        <a class="item">Signup</a>
                    <% end %>
                </div>
            </div>
            <% if logged_in? %>
                <div class="item">
                    <div class="ui primary button"><em>@<%= current_user.username %></em></div>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatMe!</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    
    <div class="ui container">
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
    <div class="content">
        <div class="summary">
            <em><span class = "username"> <%=message.user.username%></span>: </em> <%= message.message%>
        </div>
    
    </div>
</div>

app/views/users/new.html.erb
<div align="center">
    <h2>Welcome to ChatMe!</h2>
    <h4><i class="circular large blue power off icon"></i></h4>
    <h4> Sign Up! </h4>

</div>

<div class="ui placeholder segment container">
    <div class="column", style="text-align: center">
        <%= form_for(:user, :html => {class: "ui form", role: "form"}, url: signup_path) do |f| %>
            <div class="field">
                <%= f.label :username, "Username" %>
                <div class="ui left icon input">
                    <%= f.text_field :username, placeholder: "Username" %>
                    <i class="user icon"></i>
                </div>
            </div>
            <div class="field">
                <%= f.label :email, "Email" %>
                <div class="ui left icon input">
                    <%= f.text_field :email, placeholder: "Email address" %>
                    <i class="envelope icon"></i>
                </div>
            </div>
            <div class="field">
                <%= f.label :password, "Password"%>
                <div class="ui left icon input">
                    <%= f.password_field :password, placeholder: "Password" %>
                    <i class="lock icon"></i>
                </div>
            </div>
            <%= f.button "Signup", class: "ui blue submit button" %>
        <% end %>
    </div> 
</div>